# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e8bf648bdb8ad415ac1cb837d03f44914a6af485dec68d8555a3634bcc8d3a030026483f4b9438426c37da69652237dd48856257187c304be540224a48d1084

test:
  secret_key_base: 5514d60e2f583cc86c616435ba64eb4399e32c7189f1f66b9d8d826b3995a7dbeb4164b265a79727173a29e4ce5204640fecc77b655333a92ecbe779c2b3207c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
