# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c37d1e546cd1d0f35ba27d25dbcd83ea707cc3ecd749d3545e56c975f2793e510fed72f2946aab8ef12407da9ee448cb084edef035a34b8667e0ef7468683882

test:
  secret_key_base: 44086fd56f051f8376f0f74f35033b0c59ef6bbd5df5ba89c8012158df6279faa1b1896b12c7c5b00df09bcfe3ac626a43ba7f0e64545f6d4fe7dba1242b7ad2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
