// Generated by CoffeeScript 1.9.3
(function() {
  var model;

  model = {};

  model.save().done((function(_this) {
    return function() {
      return [_this, _this];
    };
  })(this));

}).call(this);
